version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  deploy:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli

      - run:
          name: Authenticate with ECR
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

            aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
              docker login --username AWS \
              --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - run:
          name: Build and Push Docker Image
          command: |
            IMAGE_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fastapi-app"
            docker build -t fastapi-app .
            docker tag fastapi-app:latest $IMAGE_REPO:latest
            docker push $IMAGE_REPO:latest

workflows:
  version: 2
  deploy-app:
    jobs:
      - deploy
